[[llmconnections]]
name = "fast"
url = "http://ai.jos.li/v1/chat/completions"
model = "Qwen3.5 (0.8B, 262k ctx, summary, Q8_K_XL)"
#model = "Gemma-4 (26B-A4B, 256k ctx, visual, Q4_K_XL)"
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.f6aWla1-8p3ZOOnVFAjMzwlgJfr3zSzCfzrDq9gVpb8"

[[llmconnections]]
name = "thinking"
url = "http://localhost:9001/v1/chat/completions"
model = "Qwen3.5 (122B-A10B, 262k ctx, coding, tool-calling, visual, Q4_K_XL)"