[*]
n-gpu-layers = 99
threads = 8
threads-batch = 2
flash-attn = on
jinja = true
batch-size = 512
ubatch-size = 512
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
no-mmap = true
no-warmup = true
cache-reuse = 64
cache-ram = 8192
kv-unified = true
fit = off

[Qwen3.5 (122B-A10B; 262k ctx; visual; Q5_K_XL)]
# url = https://huggingface.co/unsloth/Qwen3.5-122B-A10B-MTP-GGUF/resolve/main/UD-Q4_K_XL/Qwen3.5-122B-A10B-UD-Q5_K_XL-00001-of-00003.gguf
model = /mnt/models/Qwen3.5-122B-A10B-UD-Q5_K_XL-00001-of-00003.gguf
# url = https://huggingface.co/unsloth/Qwen3.5-122B-A10B-MTP-GGUF/resolve/main/mmproj-F16.gguf
mmproj = /mnt/models/Qwen3.5-122B-A10B-mmproj-F16.gguf
parallel = 1
ctx-size = 262144
spec-type = draft-mtp
spec-draft-n-max = 3

[Qwen3.5 (122B-A10B; 262k ctx; Q5_K_XL)]
# url = https://huggingface.co/unsloth/Qwen3.5-122B-A10B-MTP-GGUF/resolve/main/UD-Q4_K_XL/Qwen3.5-122B-A10B-UD-Q5_K_XL-00001-of-00003.gguf
model = /mnt/models/Qwen3.5-122B-A10B-UD-Q5_K_XL-00001-of-00003.gguf
parallel = 1
ctx-size = 262144
spec-type = draft-mtp
spec-draft-n-max = 3

[Qwen3.6 (35B-A3B; 262k ctx; Q8_K_XL)]
# url = https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
model = /mnt/models/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
# url = https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/mmproj-F16.gguf
mmproj = /mnt/models/Qwen3.6-35B-A3B-mmproj-F16.gguf
parallel = 3
ctx-size = 786432
spec-type = draft-mtp
spec-draft-n-max = 3

[DeepSeek V4 Flash (256x8.4B-A6; 128k ctx; IQ2_XXS-Q4_K mix)]
# url = https://huggingface.co/antirez/deepseek-v4-gguf/resolve/main/DeepSeek-V4-Flash-Layers37-42Q4KExperts-OtherExpertLayersIQ2XXSGateUp-Q2KDown-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix-fixed.gguf
model = /mnt/models/DeepSeek-V4-Flash-Layers37-42Q4KExperts-OtherExpertLayersIQ2XXSGateUp-Q2KDown-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix-fixed.gguf
parallel = 1
ctx-size = 131072

[Laguna S 2.1 (118B-A8B; 262k ctx; Q4_K_XL)]
# url = https://huggingface.co/unsloth/Laguna-S-2.1-GGUF/resolve/main/UD-Q4_K_XL/Laguna-S-2.1-UD-Q4_K_XL-00001-of-00003.gguf
model = /mnt/models/Laguna-S-2.1-UD-Q4_K_XL-00001-of-00003.gguf
# url = https://huggingface.co/poolside/Laguna-S-2.1-GGUF/resolve/main/laguna-s-2.1-DFlash-BF16.gguf
spec-draft-model = /mnt/models/Laguna-S-2.1-DFlash-BF16.gguf
spec-type = draft-dflash
spec-draft-n-max = 15
parallel = 1
ctx-size = 262144
# this quant bakes in the 1M rope config; uncomment for poolside's recommended 256k config
# rope-scaling = yarn
# rope-scale = 32
# yarn-orig-ctx = 8192
