[*]
n-gpu-layers = 99
threads = 8
threads-batch = 8
flash-attn = on
jinja = true
batch-size = 512
ubatch-size = 512
cache-type-k = q8_0
cache-type-v = q8_0
cache-type-k-draft = q8_0
cache-type-v-draft = q8_0
no-mmap = true
no-warmup = true
cache-reuse = 64
cache-ram = 8192
kv-unified = true
fit = off

[Qwen3.5 (122B-A10B; 262k ctx; Q5_K_XL; p2)]
# url = https://huggingface.co/unsloth/Qwen3.5-122B-A10B-MTP-GGUF/resolve/main/UD-Q4_K_XL/Qwen3.5-122B-A10B-UD-Q5_K_XL-00001-of-00003.gguf
model = /mnt/models/Qwen3.5-122B-A10B-UD-Q5_K_XL-00001-of-00003.gguf
# mmproj-url = https://huggingface.co/unsloth/Qwen3.5-122B-A10B-MTP-GGUF/resolve/main/mmproj-F16.gguf
mmproj = /mnt/models/Qwen3.5-122B-A10B-mmproj-F16.gguf
parallel = 2
ctx-size = 262144
spec-type = draft-mtp
spec-draft-n-max = 3

[Qwen3.6 (35B-A3B; 262k ctx; Q8_K_XL)]
# url = https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
model = /mnt/models/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
# mmproj-url = https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/mmproj-F16.gguf
mmproj = /mnt/models/Qwen3.6-35B-A3B-mmproj-F16.gguf
parallel = 3
ctx-size = 786432
spec-type = draft-mtp
spec-draft-n-max = 3

[Step 3.7 Flash (198B-A11B; 256k ctx; visual; IQ4_XS)]
# url = https://huggingface.co/unsloth/Step-3.7-Flash-GGUF/resolve/main/UD-IQ4_XS/Step-3.7-Flash-UD-IQ4_XS-00001-of-00003.gguf
model = /mnt/models/Step-3.7-Flash-UD-IQ4_XS-00001-of-00003.gguf
# mmproj-url = https://huggingface.co/unsloth/Step-3.7-Flash-GGUF/resolve/main/mmproj-F16.gguf
mmproj = /mnt/models/Step-3.7-Flash-mmproj-F16.gguf
parallel = 1
ctx-size = 262144

[Mistral Medium 3.5 (128B; 256k ctx; visual; Q4_K_XL)]
# url = https://huggingface.co/unsloth/Mistral-Medium-3.5-128B-GGUF/resolve/main/UD-Q4_K_XL/Mistral-Medium-3.5-128B-UD-Q4_K_XL-00001-of-00003.gguf
# mmproj-url = https://huggingface.co/unsloth/Mistral-Medium-3.5-128B-GGUF/resolve/main/mmproj-F16.gguf
model = /mnt/models/Mistral-Medium-3.5-128B-UD-Q4_K_XL-00001-of-00003.gguf
mmproj = /mnt/models/Mistral-Medium-3.5-128B-mmproj-F16.gguf
parallel = 1
ctx-size = 128000
