FROM arch:latest

#https://github.com/ServeurpersoCom/acestep.cpp
RUN git clone --recursive https://github.com/ServeurpersoCom/acestep.cpp && \
    mv acestep.cpp acestep.cpp.rocm && \
    cp -r acestep.cpp.rocm acestep.cpp.vulkan

ENV PATH="/opt/rocm/bin:${PATH}" \
    HIP_PATH=/opt/rocm \
    ROCM_PATH=/opt/rocm

RUN cd /home/arch/acestep.cpp.rocm && git submodule update --init && \
    cmake -B build \
    -DGGML_HIP=ON \
    -DAMDGPU_TARGETS=gfx1151 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_HIP_FLAGS="-mllvm --amdgpu-unroll-threshold-local=600"
RUN cd /home/arch/acestep.cpp.rocm && cmake --build build --config Release --parallel

RUN cd /home/arch/acestep.cpp.vulkan && git submodule update --init && \
    cmake -B build \
    -DGGML_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release
RUN cd /home/arch/acestep.cpp.vulkan && cmake --build build --config Release --parallel

RUN uv tool install huggingface_hub[hf_xfer]
