FROM arch:latest

USER arch
WORKDIR /home/arch

# Base installed, lets get specific
RUN yay -S --noconfirm \
  vulkan-headers \
  vulkan-icd-loader \
  vulkan-radeon \
  shaderc \
  rocwmma \
  rocm-hip-sdk \
  && sudo pacman -Scc --noconfirm

ENV PATH="/opt/rocm/bin:${PATH}" \
    HIP_PATH=/opt/rocm \
    ROCM_PATH=/opt/rocm

#ACE-STEP.CPP
#https://github.com/ServeurpersoCom/acestep.cpp

RUN git clone --recursive https://github.com/ServeurpersoCom/acestep.cpp && \
    mv acestep.cpp acestep.cpp.rocm && \
    cp -r acestep.cpp.rocm acestep.cpp.vulkan

WORKDIR /home/arch/acestep.cpp.rocm
RUN git submodule update --init && \
    cmake -B build \
    -DGGML_HIP=ON \
    -DAMDGPU_TARGETS=gfx1151 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_HIP_FLAGS="-mllvm --amdgpu-unroll-threshold-local=600"
RUN cmake --build build --config Release --parallel

WORKDIR /home/arch/acestep.cpp.vulkan
RUN git submodule update --init && \
    cmake -B build \
    -DGGML_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build --config Release --parallel

WORKDIR /home/arch

RUN uv tool install huggingface_hub[hf_xfer]
