FROM arch:latest

#https://github.com/ggml-org/llama.cpp/blob/master/docs/build.md
RUN git clone https://github.com/ggml-org/llama.cpp

ENV PATH="/opt/rocm/bin:${PATH}" \
    HIP_PATH=/opt/rocm \
    ROCM_PATH=/opt/rocm

RUN cd /home/arch/llama.cpp && cmake -B build \
    -DGGML_HIP=ON \
    -DGGML_NATIVE=ON \
    -DGGML_HIP_ROCWMMA_FATTN=ON \
    -DAMDGPU_TARGETS=gfx1151 \
    -DGGML_CUDA_FA_ALL_QUANTS=ON \
    -DGGML_CUDA_ENABLE_UNIFIED_MEMORY=ON \
    -DGGML_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_HIP_FLAGS="-mllvm --amdgpu-unroll-threshold-local=600"
RUN cd /home/arch/llama.cpp && cmake --build build --config Release --parallel
