FROM arch:latest

#https://github.com/ServeurpersoCom/acestep.cpp
RUN git -c http.version=HTTP/1.1 clone --recursive https://github.com/ServeurpersoCom/acestep.cpp && \
    mv acestep.cpp acestep.cpp.rocm && \
    cp -r acestep.cpp.rocm acestep.cpp.vulkan

ENV ROCM_PATH=/opt/rocm/core \
    HIP_PATH=/opt/rocm/core \
    PATH="/opt/rocm/core/bin:/opt/rocm/core/lib/llvm/bin:${PATH}" \
    ROCBLAS_USE_HIPBLASLT=1

RUN cd /home/arch/acestep.cpp.rocm && git submodule update --init && \
    cmake -B build \
    -DGGML_HIP=ON \
    -DAMDGPU_TARGETS=gfx1151 \
    -DCMAKE_BUILD_TYPE=Release
RUN cd /home/arch/acestep.cpp.rocm && cmake --build build --config Release --parallel

RUN cd /home/arch/acestep.cpp.vulkan && git submodule update --init && \
    cmake -B build \
    -DGGML_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release
RUN cd /home/arch/acestep.cpp.vulkan && cmake --build build --config Release --parallel

RUN uv tool install huggingface_hub[hf_xfer]
