FROM arch:latest

USER arch
WORKDIR /home/arch

# Base installed, lets get specific
RUN yay -S --noconfirm \
  vulkan-headers \
  vulkan-icd-loader \
  vulkan-radeon \
  shaderc \
  rocwmma \
  rocm-hip-sdk \
  && sudo pacman -Scc --noconfirm

ENV PATH="/opt/rocm/bin:${PATH}" \
    HIP_PATH=/opt/rocm \
    ROCM_PATH=/opt/rocm

#STABLE-DIFFUSION.CPP
#https://github.com/leejet/stable-diffusion.cpp
    
RUN git clone --recursive https://github.com/leejet/stable-diffusion.cpp && \
    mv stable-diffusion.cpp stable-diffusion.cpp.rocm && \
    cp -r stable-diffusion.cpp.rocm stable-diffusion.cpp.vulkan

WORKDIR /home/arch/stable-diffusion.cpp.rocm
RUN cmake -B build -G "Ninja" \
    -DCMAKE_C_COMPILER=/opt/rocm/lib/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=/opt/rocm/lib/llvm/bin/clang++ \
    -DSD_HIPBLAS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DAMDGPU_TARGETS=gfx1151 \
    -DGPU_TARGETS=gfx1151 \
    -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
    -DGGML_CUDA_ENABLE_UNIFIED_MEMORY=ON \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
RUN cmake --build build --config Release --parallel

WORKDIR /home/arch/stable-diffusion.cpp.vulkan
RUN cmake -B build -G "Ninja" \
    -DSD_VULKAN=ON
RUN cmake --build build --config Release --parallel

#https://github.com/daniandtheweb/sd.cpp-webui
WORKDIR /home/arch/
RUN git clone https://github.com/daniandtheweb/sd.cpp-webui.git && \
    mv sd.cpp-webui sd.cpp-webui.rocm && \
    cp -r sd.cpp-webui.rocm sd.cpp-webui.vulkan
    
RUN cp stable-diffusion.cpp.rocm/build/bin/sd-cli sd.cpp-webui.rocm && \
    cp stable-diffusion.cpp.rocm/build/bin/sd-server sd.cpp-webui.rocm && \
    cp stable-diffusion.cpp.vulkan/build/bin/sd-cli sd.cpp-webui.vulkan && \
    cp stable-diffusion.cpp.vulkan/build/bin/sd-server sd.cpp-webui.vulkan

# Create model subdirectories expected by sd.cpp-webui config
RUN for dir in sd.cpp-webui.rocm sd.cpp-webui.vulkan; do \
    mkdir -p $dir/models/{checkpoints,unet,vae,text_encoders,embeddings,loras,taesd,photomaker,upscale_models,controlnet}; \
    done

WORKDIR /home/arch/sd.cpp-webui.rocm
RUN chmod a+x sdcpp_webui.sh && \
    uv venv --python 3.13 --seed venv && \
    source venv/bin/activate && \
    uv pip install -r requirements.txt && \
    uv pip install requests

WORKDIR /home/arch/sd.cpp-webui.vulkan
RUN chmod a+x sdcpp_webui.sh && \
    uv venv --python 3.13 --seed venv && \
    source venv/bin/activate && \
    uv pip install -r requirements.txt && \
    uv pip install requests
